from .argument_creation import create_thesis_with_arguments
from .argument_rebuttal import create_counter_for_thesis
from .claim_duplicates import (
    compute_cosine_similarity,
    duplicate_candidates_for_claim,
    generate_claim_embedding,
    generate_claim_embedding_vector,
    rebuild_claim_similarities,
    refresh_claim_similarity,
    review_duplicate_pair,
)
from .claim_graph import (
    add_evidence_to_claim,
    calculate_claim_score,
    calculate_thesis_claim_scores,
    compute_bayesian_vote_score,
    compute_evidence_score,
    compute_pagerank_scores,
    cast_vote_for_claim,
    create_claim_for_thesis,
    create_claim_from_argument,
    create_claim_from_counter,
    merge_claims,
    rebuild_claim_scores,
    update_claim_with_revision,
)
from .claim_inference import (
    ensure_default_inference_rules,
    rebuild_all_inference,
    rebuild_claim_contradictions,
    rebuild_claim_inferences,
    rebuild_claim_support_closure,
    rebuild_thesis_inference,
    rebuild_thesis_inference_safe,
)
from .claim_normalization import (
    canonicalize_entity_name,
    get_or_create_claim_entity,
    get_or_create_claim_predicate,
    normalize_claim,
    normalize_claim_safe,
    parse_claim_text_to_triple,
    rebuild_claim_normalizations,
)

__all__ = [
    "add_evidence_to_claim",
    "calculate_claim_score",
    "calculate_thesis_claim_scores",
    "compute_bayesian_vote_score",
    "compute_evidence_score",
    "compute_cosine_similarity",
    "compute_pagerank_scores",
    "cast_vote_for_claim",
    "create_claim_for_thesis",
    "create_claim_from_argument",
    "create_claim_from_counter",
    "create_counter_for_thesis",
    "create_thesis_with_arguments",
    "duplicate_candidates_for_claim",
    "generate_claim_embedding",
    "generate_claim_embedding_vector",
    "merge_claims",
    "ensure_default_inference_rules",
    "rebuild_all_inference",
    "rebuild_claim_similarities",
    "rebuild_claim_contradictions",
    "rebuild_claim_inferences",
    "rebuild_claim_scores",
    "rebuild_claim_support_closure",
    "rebuild_thesis_inference",
    "rebuild_thesis_inference_safe",
    "refresh_claim_similarity",
    "review_duplicate_pair",
    "canonicalize_entity_name",
    "get_or_create_claim_entity",
    "get_or_create_claim_predicate",
    "normalize_claim",
    "normalize_claim_safe",
    "parse_claim_text_to_triple",
    "rebuild_claim_normalizations",
    "update_claim_with_revision",
]
