# Generated by Django 5.2.11 on 2026-03-01 14:18

import thinking.content_status
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0003_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="counter",
            name="status",
            field=models.CharField(
                choices=[
                    (thinking.content_status.ContentStatus["ACTIVE"], "Active"),
                    (
                        thinking.content_status.ContentStatus["PENDING_REVIEW"],
                        "Pending Review",
                    ),
                    (thinking.content_status.ContentStatus["REJECTED"], "Rejected"),
                    (thinking.content_status.ContentStatus["ARCHIVED"], "Archived"),
                ],
                db_index=True,
                default=thinking.content_status.ContentStatus["ACTIVE"],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="thesis",
            name="status",
            field=models.CharField(
                choices=[
                    (thinking.content_status.ContentStatus["ACTIVE"], "Active"),
                    (
                        thinking.content_status.ContentStatus["PENDING_REVIEW"],
                        "Pending Review",
                    ),
                    (thinking.content_status.ContentStatus["REJECTED"], "Rejected"),
                    (thinking.content_status.ContentStatus["ARCHIVED"], "Archived"),
                ],
                db_index=True,
                default=thinking.content_status.ContentStatus["ACTIVE"],
                max_length=32,
            ),
        ),
    ]
