# Generated by Django 5.2.11 on 2026-03-03 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0006_contentreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentreport",
            name="uniq_open_report_per_reporter_target",
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "target_type", "target_id", "status"),
                name="uniq_report_per_reporter_target_status",
            ),
        ),
    ]
