# Generated by Django 5.2.11 on 2026-03-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_content_report_targets_forward(apps, schema_editor):
    ContentReport = apps.get_model("thinking", "ContentReport")
    Thesis = apps.get_model("thinking", "Thesis")
    Counter = apps.get_model("thinking", "Counter")
    db_alias = schema_editor.connection.alias

    thesis_ids = set(Thesis.objects.using(db_alias).values_list("id", flat=True))
    counter_ids = set(Counter.objects.using(db_alias).values_list("id", flat=True))
    stale_report_ids = []

    for report in ContentReport.objects.using(db_alias).all().iterator(chunk_size=500):
        target_type = str(report.target_type or "").strip().lower()
        target_id_raw = str(report.target_id or "").strip()
        try:
            target_id = int(target_id_raw)
        except (TypeError, ValueError):
            stale_report_ids.append(report.id)
            continue

        if target_type == "thesis" and target_id in thesis_ids:
            ContentReport.objects.using(db_alias).filter(pk=report.pk).update(
                thesis_id=target_id
            )
            continue
        if target_type == "counter" and target_id in counter_ids:
            ContentReport.objects.using(db_alias).filter(pk=report.pk).update(
                counter_id=target_id
            )
            continue
        stale_report_ids.append(report.id)

    if stale_report_ids:
        ContentReport.objects.using(db_alias).filter(id__in=stale_report_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "thinking",
            "0007_remove_contentreport_uniq_open_report_per_reporter_target_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentreport",
            name="uniq_report_per_reporter_target_status",
        ),
        migrations.RemoveIndex(
            model_name="contentreport",
            name="thinking_co_target__baa220_idx",
        ),
        migrations.AddField(
            model_name="contentreport",
            name="counter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reports",
                to="thinking.counter",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="thesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reports",
                to="thinking.thesis",
            ),
        ),
        migrations.RunPython(
            code=migrate_content_report_targets_forward,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="target_id",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="target_type",
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["thesis", "status"], name="thinking_co_thesis__410f37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["counter", "status"], name="thinking_co_counter_cd383a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("thesis__isnull", False), ("counter__isnull", True)),
                    models.Q(("thesis__isnull", True), ("counter__isnull", False)),
                    _connector="OR",
                ),
                name="content_report_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("thesis__isnull", False)),
                fields=("reporter", "thesis", "status"),
                name="uniq_report_per_reporter_thesis_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("counter__isnull", False)),
                fields=("reporter", "counter", "status"),
                name="uniq_report_per_reporter_counter_status",
            ),
        ),
    ]
