# Generated by Django 5.2.11 on 2026-03-06 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "thinking",
            "0008_remove_contentreport_uniq_report_per_reporter_target_status_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentreport",
            name="uniq_report_per_reporter_thesis_status",
        ),
        migrations.RemoveConstraint(
            model_name="contentreport",
            name="uniq_report_per_reporter_counter_status",
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "thesis", "status"),
                name="uniq_report_per_reporter_thesis_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "counter", "status"),
                name="uniq_report_per_reporter_counter_status",
            ),
        ),
    ]
