# Generated by Django 5.2.11 on 2026-03-09 05:48

import django.db.models.deletion
import thinking.content_status
from django.conf import settings
from django.db import migrations, models


def seed_claim_relation_types(apps, schema_editor):
    del schema_editor
    ClaimRelationType = apps.get_model("thinking", "ClaimRelationType")
    entries = (
        ("support", "Support"),
        ("oppose", "Oppose"),
        ("clarify", "Clarify"),
        ("question", "Question"),
    )
    for code, label in entries:
        ClaimRelationType.objects.update_or_create(
            code=code,
            defaults={"label": label},
        )


def unseed_claim_relation_types(apps, schema_editor):
    del schema_editor
    ClaimRelationType = apps.get_model("thinking", "ClaimRelationType")
    ClaimRelationType.objects.filter(
        code__in=("support", "oppose", "clarify", "question")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0011_counter_counter_parent_not_self"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (thinking.content_status.ContentStatus["ACTIVE"], "Active"),
                            (
                                thinking.content_status.ContentStatus["PENDING_REVIEW"],
                                "Pending Review",
                            ),
                            (
                                thinking.content_status.ContentStatus["REJECTED"],
                                "Rejected",
                            ),
                            (
                                thinking.content_status.ContentStatus["ARCHIVED"],
                                "Archived",
                            ),
                        ],
                        db_index=True,
                        default=thinking.content_status.ContentStatus["ACTIVE"],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimRelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["label", "id"],
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="thinking.thesis",
            ),
        ),
        migrations.AddField(
            model_name="claimrelation",
            name="source_claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_relations",
                to="thinking.claim",
            ),
        ),
        migrations.AddField(
            model_name="claimrelation",
            name="target_claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_relations",
                to="thinking.claim",
            ),
        ),
        migrations.AddField(
            model_name="claimrelation",
            name="relation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claim_relations",
                to="thinking.claimrelationtype",
            ),
        ),
        migrations.RunPython(seed_claim_relation_types, unseed_claim_relation_types),
    ]
