# Generated by Django 5.2.11 on 2026-03-09 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0013_claimevidence_claimrevision_claimvote_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
