# Generated by Django 5.2.11 on 2026-03-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0014_claimrelation_uniq_claim_relation_edge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateClaimMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "argument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_mappings",
                        to="thinking.argument",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_mappings",
                        to="thinking.claim",
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_mappings",
                        to="thinking.counter",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_mappings",
                        to="thinking.thesis",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("argument__isnull", False), ("counter__isnull", True)
                            ),
                            models.Q(
                                ("argument__isnull", True), ("counter__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="debate_claim_mapping_exactly_one_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("argument__isnull", False)),
                        fields=("argument",),
                        name="uniq_debate_claim_mapping_argument",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("counter__isnull", False)),
                        fields=("counter",),
                        name="uniq_debate_claim_mapping_counter",
                    ),
                ],
            },
        ),
    ]
