# Generated by Django 5.2.11 on 2026-03-09 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0015_debateclaimmapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimCanonical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_for",
                        to="thinking.claim",
                    ),
                ),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_record",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["canonical_claim", "created_at"],
                        name="thinking_cl_canonic_6c9e54_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimMergeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merged_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "merged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_merge_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_sources",
                        to="thinking.claim",
                    ),
                ),
                (
                    "target_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_targets",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-merged_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["source_claim", "merged_at"],
                        name="thinking_cl_source__7fddb4_idx",
                    ),
                    models.Index(
                        fields=["target_claim", "merged_at"],
                        name="thinking_cl_target__69bf20_idx",
                    ),
                ],
            },
        ),
    ]
