# Generated by Django 5.2.11 on 2026-03-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0016_claimcanonical_claimmergelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_score", models.FloatField(default=0.0)),
                ("evidence_score", models.FloatField(default=0.0)),
                ("support_score", models.FloatField(default=0.0)),
                ("oppose_score", models.FloatField(default=0.0)),
                ("graph_score", models.FloatField(default=0.0)),
                ("final_score", models.FloatField(db_index=True, default=0.0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-final_score", "claim_id"],
            },
        ),
    ]
