# Generated by Django 5.2.11 on 2026-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0017_claimscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimevidence",
            name="citation_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="claimevidence",
            name="source_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="claimevidence",
            name="trust_score",
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AddField(
            model_name="claimscore",
            name="bayesian_vote_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="claimscore",
            name="pagerank_score",
            field=models.FloatField(default=0.0),
        ),
    ]
