# Generated by Django 5.2.11 on 2026-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0018_claimevidence_citation_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimevidence",
            name="citation_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
