# Generated by Django 5.2.11 on 2026-03-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0019_alter_claimevidence_citation_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_vector", models.JSONField(default=list)),
                ("embedding_model", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "claim_id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDuplicateReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("merge", "Merge"), ("ignore", "Ignore")],
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now=True)),
                (
                    "claim_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reviews_left",
                        to="thinking.claim",
                    ),
                ),
                (
                    "claim_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reviews_right",
                        to="thinking.claim",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_duplicate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("claim_a__lt", models.F("claim_b"))),
                        name="claim_duplicate_review_canonical_pair_order",
                    ),
                    models.UniqueConstraint(
                        fields=("claim_a", "claim_b"),
                        name="uniq_claim_duplicate_review_pair",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField(db_index=True)),
                ("detected_at", models.DateTimeField(auto_now=True)),
                (
                    "claim_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_left",
                        to="thinking.claim",
                    ),
                ),
                (
                    "claim_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_right",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_score", "-detected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["claim_a", "-similarity_score"],
                        name="thinking_cl_claim_a_9a07e1_idx",
                    ),
                    models.Index(
                        fields=["claim_b", "-similarity_score"],
                        name="thinking_cl_claim_b_f618db_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("claim_a__lt", models.F("claim_b"))),
                        name="claim_similarity_canonical_pair_order",
                    ),
                    models.UniqueConstraint(
                        fields=("claim_a", "claim_b"), name="uniq_claim_similarity_pair"
                    ),
                ],
            },
        ),
    ]
