# Generated by Django 5.2.11 on 2026-03-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0020_claimembedding_claimduplicatereview_claimsimilarity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("canonical_name", models.CharField(max_length=200, unique=True)),
                ("entity_type", models.CharField(default="concept", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["canonical_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimPredicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimTriple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triples",
                        to="thinking.claim",
                    ),
                ),
                (
                    "object_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_triples",
                        to="thinking.claimentity",
                    ),
                ),
                (
                    "predicate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triples",
                        to="thinking.claimpredicate",
                    ),
                ),
                (
                    "subject_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_triples",
                        to="thinking.claimentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimNormalized",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalization_method", models.CharField(max_length=120)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized",
                        to="thinking.claim",
                    ),
                ),
                (
                    "triple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_claims",
                        to="thinking.claimtriple",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "claim_id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_text", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["alias_text", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("claim", "alias_text"), name="uniq_claim_alias_text"
                    )
                ],
            },
        ),
    ]
