# Generated by Django 5.2.11 on 2026-03-09 09:44

import django.db.models.deletion
from django.db import migrations, models


def seed_inference_rules(apps, schema_editor):
    claim_inference_rule = apps.get_model("thinking", "ClaimInferenceRule")
    rows = (
        {
            "name": "causal-chain-increases-risk",
            "pattern_predicate_a": "cause",
            "pattern_predicate_b": "cause",
            "inferred_predicate": "increase-risk",
            "confidence_weight": 0.78,
        },
        {
            "name": "preventive-chain-reduces-risk",
            "pattern_predicate_a": "prevent",
            "pattern_predicate_b": "cause",
            "inferred_predicate": "prevent",
            "confidence_weight": 0.72,
        },
    )
    for row in rows:
        claim_inference_rule.objects.get_or_create(name=row["name"], defaults=row)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("thinking", "0021_claimentity_claimpredicate_claimtriple_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimInferenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("pattern_predicate_a", models.CharField(max_length=120)),
                ("pattern_predicate_b", models.CharField(max_length=120)),
                ("inferred_predicate", models.CharField(max_length=120)),
                ("confidence_weight", models.FloatField(default=0.5)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClaimContradiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contradiction_type", models.CharField(max_length=120)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "claim_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions_left",
                        to="thinking.claim",
                    ),
                ),
                (
                    "claim_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions_right",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "claim_a_id", "claim_b_id"],
                "indexes": [
                    models.Index(
                        fields=["claim_a", "contradiction_type"],
                        name="thinking_cl_claim_a_134ba7_idx",
                    ),
                    models.Index(
                        fields=["claim_b", "contradiction_type"],
                        name="thinking_cl_claim_b_6c418e_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("claim_a__lt", models.F("claim_b"))),
                        name="claim_contradiction_canonical_pair_order",
                    ),
                    models.UniqueConstraint(
                        fields=("claim_a", "claim_b", "contradiction_type"),
                        name="uniq_claim_contradiction_pair_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimInference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "inferred_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_inferences",
                        to="thinking.claim",
                    ),
                ),
                (
                    "source_claim_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_sources_a",
                        to="thinking.claim",
                    ),
                ),
                (
                    "source_claim_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_sources_b",
                        to="thinking.claim",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_inferences",
                        to="thinking.claiminferencerule",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["source_claim_a", "created_at"],
                        name="thinking_cl_source__4b0237_idx",
                    ),
                    models.Index(
                        fields=["source_claim_b", "created_at"],
                        name="thinking_cl_source__d16261_idx",
                    ),
                    models.Index(
                        fields=["inferred_claim", "created_at"],
                        name="thinking_cl_inferre_fd3116_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_claim_a", models.F("source_claim_b")),
                            _negated=True,
                        ),
                        name="claim_inference_distinct_sources",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "source_claim_a",
                            "source_claim_b",
                            "inferred_claim",
                            "rule",
                        ),
                        name="uniq_claim_inference_rule_application",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimSupportClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_depth", models.PositiveIntegerField(default=1)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "source_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_closure_sources",
                        to="thinking.claim",
                    ),
                ),
                (
                    "target_claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_closure_targets",
                        to="thinking.claim",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "support_depth",
                    "-confidence",
                    "source_claim_id",
                    "target_claim_id",
                ],
                "indexes": [
                    models.Index(
                        fields=["source_claim", "support_depth"],
                        name="thinking_cl_source__4c0c22_idx",
                    ),
                    models.Index(
                        fields=["target_claim", "support_depth"],
                        name="thinking_cl_target__49bdb2_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_claim", models.F("target_claim")), _negated=True
                        ),
                        name="claim_support_closure_distinct_nodes",
                    ),
                    models.UniqueConstraint(
                        fields=("source_claim", "target_claim"),
                        name="uniq_claim_support_closure_pair",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_inference_rules, noop_reverse),
    ]
